# Generated by Django 5.0 on 2023-12-19 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCompleto', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('crm', models.CharField(max_length=10, unique=True, verbose_name='CRM')),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.especialidade')),
            ],
        ),
    ]
